name: osl-bot-jobs
channels:
  - conda-forge
dependencies:
  - pip
  - discord.py
  - python-dotenv
  - requests
  # dev
  - black
  - flake8
  - coverage
  - sphinx
  - twine
  - pytest
  - pytest-runner
  - pytest-cov
  - pre-commit
  - pip:
    - replit
